name: Javadocs Generator

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  javadocs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Clean up folder
      run: rm -rf Slimefun4/
    - name: Clone repository
      run: git clone https://github.com/TheBusyBiscuit/Slimefun4
    - name: Set up Java 9 JDK
      uses: actions/setup-java@master
      with:
        java-version: 9.0.4
    - name: Generate Javadocs
      run: cd Slimefun4 && mvn javadoc:javadoc
    - name: Push to repository
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        push-branch: 'master'
        commit-message: 'Updated Javadocs'
        force-add: 'true'
        files: Slimefun4/docs
        name: TheBusyBot
        email: ${{ secrets.BOT_EMAIL }}
