name: Javadocs Generator

on: push

jobs:
  javadocs:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      run: 'git clone https://github.com/TheBusyBiscuit/Slimefun4 && cd Slimefun4'
    - name: Set up JDK 1.9
      uses: giltene/setup-java@master
      with:
        java-version: 9.0.4
    - name: Generate Javadocs
      run: mvn javadoc:javadoc
    - name: Push to repository
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        push-branch: 'master'
        commit-message: 'Updated Javadocs'
        force-add: 'true'
        files: Slimefun4/docs
        name: TheBusyBot
        email: ${{ secrets.BOT_EMAIL }}
